# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=50)),
                ('rating', models.FloatField(default=0)),
                ('review', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookEntity',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Book')),
            ],
        ),
    ]
